### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple when printing the user information table when running as a shell executable on Mac and on Windows when creating a new user

### ISSUE THREAD

**Issue by AlvinKuruvilla** [AlvinKuruvilla/kmlog#13]
After submitting the information needed to create a new user, KMLogger tries to display the information as a ```PrettyTable```. The same is also true when displaying a returning user's saved information. When running locally this seems to work without issue. However, when running as a standalone shell executable or on Windows this functionality results in: 
 ```python
Traceback (most recent call last):
  File "tui.py", line 164, in <module>
  File "tui.py", line 135, in run
  File "base/user_ops/yml_ops.py", line 111, in create_user
  File "base/user_ops/yml_ops.py", line 65, in tuple_to_dict
TypeError: list indices must be integers or slices, not tuple
```

**Comment by AlvinKuruvilla** [comment]
No longer relevant
